// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yechisulpkleqnweyzpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllY2hpc3VscGtsZXFud2V5enB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk5OTYxODAsImV4cCI6MjA4NTU3MjE4MH0.waVdpwx5W6ZCvCdhNnjnQWrbbaibDlRift1SlDmtbR0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});